### ISSUE TITLE
Problem running "npm run build"

### ISSUE THREAD

**Issue by andrecgro** [raphamorim/write-code-every-day#51] opened 2015-08-03 03:47 UTC
Everytime I try to run "npm run build" command, creating a branch or not, all the code lines of "index.html" are deleted and I could not put my push my name as a challanger.

**Comment by raphamorim** [comment] 2015-08-03 04:43
I'll check this. Can you display the log?

(If you wanna,  you can just add your name in `challengers.js` and send the PR. I'll make the build)

**Comment by andrecgro** [comment] 2015-08-03 05:26
Right, I'll do this way, just adding my name and sending the PR.
Actually I don't have an log cause npm doesn't tells me it's one error anymore.
In my first tries it was something like "You don't have the index.ejs file" and it generated a log but I've found the solution and it wast just create the file manually.
Now, it just says "Unhandled rejection Error: API rate limit exceeded for 191.7.147.193. <But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.>"

**Comment by raphamorim** [comment] 2015-08-03 05:32
You are trying this on master branch?

This error: "Unhandled rejection Error: API rate limit exceeded for ..." is caused by the script. Because it don't authenticate with GitHub Api. So have a limit for requests (I'll solve this removing `npm run build` from guide)

**Comment by andrecgro** [comment] 2015-08-03 05:35
I've tried first on "my-branch", got errors, deleted this branch and tried on master branch

**Comment by andrecgro** [comment] 2015-08-03 19:09
Well, I saw that I haven't installed GIT on my computer yet, just GitHub and I think that's the reason for the error above. So I installed it and tried to put my name in challengers.js and build again but I get another error. Sending the log file.
![npm-debug](https://cloud.githubusercontent.com/assets/7674405/9045503/e9f2a6f8-39f9-11e5-9acd-37eaaac70756.png)

**Comment by raphamorim** [comment] 2015-08-05 14:01
Hmmm. I'll look this problem on Windows tonight. For while forget `npm run build`, I've removed this command from readme guide :)

So I'll close this issue.

**Closed by raphamorim** 2015-08-05 14:01 UTC
